AllCops:
  Exclude:
    - 'bin/*'
    - 'db/*'
    - 'script/*'
    - 'lib/tasks/cucumber.rake'
    - Guardfile

Metrics/LineLength:
  Max: 110

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false