AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'lib/tasks/cucumber.rake'
    - Guardfile
    - 'hooks/**/*'

Metrics/LineLength:
  Max: 110

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/IndentHash:
  Enabled: false

Style/TrailingComma:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 23
