AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'lib/tasks/cucumber.rake'
    - Gemfile
    - 'hooks/**/*'
    - 'vendor/bundle/**/*'

Rails:
  Enabled: true

Rails/TimeZone:
  Enabled: false

Metrics/LineLength:
  Max: 110

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Exclude:
    - 'app/models/git_repository.rb'

Metrics/AbcSize:
  Max: 20

Style/IndentArray:
  EnforcedStyle: consistent

Style/NestedParenthesizedCalls:
  Enabled: false  # TODO: Enable when possible to configure for method arity.

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: semantic
  Exclude:
    - 'spec/**/*'

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/MultilineBlockChain:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic
  Exclude:
    - 'app/use_cases/link_ticket.rb'

Style/DoubleNegation:
  Enabled: false

inherit_from: .rubocop_todo.yml
