AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'lib/tasks/cucumber.rake'
    - Guardfile
    - 'hooks/**/*'
    - 'features/step_definitions/debug_steps.rb'

Metrics/LineLength:
  Max: 110

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: semantic
  Enabled: true

Style/TrailingComma:
  EnforcedStyleForSingleline: no_comma
  EnforcedStyleForMultiline: comma
  Enabled: true

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 26
