AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'lib/tasks/cucumber.rake'
    - Guardfile
    - Gemfile
    - 'hooks/**/*'
    - 'vendor/bundle/**/*'

Rails:
  Enabled: true

Rails/TimeZone:
  Enabled: false

Metrics/LineLength:
  Max: 110

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

Style/NestedParenthesizedCalls:
  Enabled: false  # Disable until it's possible to configure for method arity.

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: semantic
  Enabled: true

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/MultilineBlockChain:
  Enabled: false

inherit_from: .rubocop_todo.yml
