AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'lib/tasks/cucumber.rake'
    - Gemfile
    - 'hooks/**/*'
    - 'vendor/bundle/**/*'

Performance/TimesMap:
  Enabled: false  # TODO: Remove when fix released: https://github.com/bbatsov/rubocop/commit/162febe3da7cfac6cdd5a6c28bfc21385ad3c729

Rails:
  Enabled: true

Rails/TimeZone:
  Enabled: false

Metrics/LineLength:
  Max: 110

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 20

Style/IndentArray:
  EnforcedStyle: consistent

Style/NestedParenthesizedCalls:
  Enabled: false  # TODO: Enable when possible to configure for method arity.

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  EnforcedStyle: semantic

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/MultilineBlockChain:
  Enabled: false

inherit_from: .rubocop_todo.yml
