version: '2.4'
services:
  web:
    build:
      context: .
    image: shipment_tracker
    command: >
      sh -c 'bundle exec rake db:structure:load && \
             exec bundle exec unicorn --config-file config/unicorn.rb'
    environment:
      AUTH0_CLIENT_ID: Y9ltgcdXUkNA4hRDWuP0nxDaZVdIskBM
      AUTH0_CLIENT_SECRET:
      AUTH0_CONNECTION: fundingcircle.com
      AUTH0_DOMAIN: fundingcircle.auth0.com
      DATABASE_URL: postgresql://postgres:postgres@postgres/shipment_tracker
      GITHUB_REPO_READ_TOKEN:
      GIT_REPOSITORY_CACHE_DIR: /tmp/git
      PORT_HTTP: 1201
      PROTECT_STDOUT: 'true'
      RAILS_ENV: "${RAILS_ENV:-development}"
      SSH_USER: git
      SSH_PUBLIC_KEY:
      SSH_PRIVATE_KEY:
    ports:
      - 127.0.0.1:1201:1201
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - git:/tmp/git
    healthcheck:
      test: curl localhost:1201/heartbeat
      interval: 10s

  update_git_loop:
    image: shipment_tracker
    command: bundle exec rake jobs:update_git_loop
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres/shipment_tracker
      GIT_REPOSITORY_CACHE_DIR: /tmp/git
      PROTECT_STDOUT: 'true'
      RAILS_ENV: "${RAILS_ENV:-development}"
      SSH_USER: git
      SSH_PUBLIC_KEY:
      SSH_PRIVATE_KEY:
    tty: true
    stdin_open: true
    user: root
    depends_on:
      web:
        condition: service_healthy
    volumes:
      - git:/tmp/git

  update_events_loop:
    image: shipment_tracker
    command: bundle exec rake jobs:update_events_loop
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres/shipment_tracker
      PROTECT_STDOUT: 'true'
      RAILS_ENV: "${RAILS_ENV:-development}"
    tty: true
    stdin_open: true
    depends_on:
      web:
        condition: service_healthy

  postgres:
    image: postgres:9.4-alpine
    environment:
      POSTGRES_DB: shipment_tracker
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready --host=localhost --dbname=shipment_tracker --username=postgres || exit 1
      interval: 10s

volumes:
  pgdata:
  git:
