version: '2.4'
services:
  web:
    build:
      context: .
    image: shipment_tracker
    command: >
      sh -c 'bundle exec rake db:structure:load && \
             exec bundle exec rails server --binding=0.0.0.0 --port 1201'
    environment:
      AUTH0_CLIENT_ID: Y9ltgcdXUkNA4hRDWuP0nxDaZVdIskBM
      AUTH0_CLIENT_SECRET:
      AUTH0_CONNECTION: fundingcircle.com
      AUTH0_DOMAIN: fundingcircle.auth0.com
      GITHUB_REPO_READ_TOKEN:
      GIT_REPOSITORY_CACHE_DIR: /tmp/git
      PROTECT_STDOUT: 'true'
      RAILS_ENV: "${RAILS_ENV:-development}"
      SHIPMENT_TRACKER_DATABASE_HOST: postgres
      SHIPMENT_TRACKER_DATABASE_NAME: shipment_tracker
      SHIPMENT_TRACKER_DATABASE_PASSWORD: postgres
      SHIPMENT_TRACKER_DATABASE_USERNAME: postgres
      SSH_USER: git
      SSH_PUBLIC_KEY:
      SSH_PRIVATE_KEY:
    ports:
      - 127.0.0.1:1201:1201
    depends_on:
      - postgres
    volumes:
      - git:/tmp/git

  update_git_loop:
    image: shipment_tracker
    command: sh -c 'bundle exec rake db:create db:migrate && exec bundle exec rake jobs:update_git_loop'
    environment:
      GIT_REPOSITORY_CACHE_DIR: /tmp/git
      PROTECT_STDOUT: 'true'
      RAILS_ENV: "${RAILS_ENV:-development}"
      SHIPMENT_TRACKER_DATABASE_HOST: postgres
      SHIPMENT_TRACKER_DATABASE_NAME: shipment_tracker
      SHIPMENT_TRACKER_DATABASE_PASSWORD: postgres
      SHIPMENT_TRACKER_DATABASE_USERNAME: postgres
      SSH_USER: git
      SSH_PUBLIC_KEY:
      SSH_PRIVATE_KEY:
    tty: true
    stdin_open: true
    user: root
    depends_on:
      - postgres
    volumes:
      - git:/tmp/git

  update_events_loop:
    image: shipment_tracker
    command: sh -c 'bundle exec rake db:create db:migrate && exec bundle exec rake jobs:update_events_loop'
    environment:
      PROTECT_STDOUT: 'true'
      RAILS_ENV: "${RAILS_ENV:-development}"
      SHIPMENT_TRACKER_DATABASE_HOST: postgres
      SHIPMENT_TRACKER_DATABASE_NAME: shipment_tracker
      SHIPMENT_TRACKER_DATABASE_PASSWORD: postgres
      SHIPMENT_TRACKER_DATABASE_USERNAME: postgres
    tty: true
    stdin_open: true
    depends_on:
      - postgres

  postgres:
    image: postgres:9.4-alpine
    environment:
      POSTGRES_DB: shipment_tracker
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  git:
