version: 2

jobs:
  build:
    branches:
      ignore:
        - /dependabot\/.*/
    docker:
      - image: circleci/ruby:2.3.6
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
          SHIPMENT_TRACKER_DATABASE_NAME: shipment_tracker_test
          SHIPMENT_TRACKER_DATABASE_HOST: 127.0.0.1
          SHIPMENT_TRACKER_DATABASE_USERNAME: st_test
          SHIPMENT_TRACKER_DATABASE_PASSWORD: ""
      - image: circleci/postgres:9.4-alpine
        environment:
          POSTGRES_DB: shipment_tracker_test
          POSTGRES_USER: st_test
          POSTGRES_PASSWORD: ""
    steps:
      - run: sudo apt-get install -y cmake postgresql-client
      - checkout
      - run: cp .env.development.example .env.test
      - run:  gem install bundler
      - restore_cache:
          key: shipment_tracker-gems-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install
      - save_cache:
          key: shipment_tracker-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: bundle exec rake db:create_database_yml
      - run: bundle exec rake db:setup
      - run: bundle exec rake spec
      - run: bundle exec rake cucumber
      - run: bundle exec rubocop -D
      - run: bundle exec rake codeclimate
      - run:
          name: Submit build status
          command: |
            if [ "$CIRCLE_PROJECT_USERNAME" == "FundingCircle" ]; then
              curl --header 'Accept: application/json' https://circleci.com/api/v1/project/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/$CIRCLE_BUILD_NUM?circle-token=$CIRCLE_TOKEN \
              | curl --request POST --header 'Content-Type:application/json' --data @- --fail $SHIPMENT_TRACKER_POST_URL
            fi
